# Generated by Django 2.2.5 on 2021-01-29 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
