# Generated by Django 2.2.5 on 2021-02-02 10:14

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('cat_app', '0002_delete_customuser'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('catobj', django.db.models.manager.Manager()),
            ],
        ),
    ]
