# Generated by Django 2.2.5 on 2021-02-12 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cat_app', '0007_auto_20210206_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='prodcat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='cat_app.Category'),
        ),
    ]
