# Generated by Django 2.2.5 on 2021-01-29 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cat_app', '0002_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('itm_qty', models.PositiveIntegerField()),
                ('total_amt', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[(1, 'on hold'), (2, 'delivered'), (3, 'shipped'), (4, 'ready to ship')], default=1, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('ord_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prod_itm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cat_app.Products')),
            ],
        ),
    ]
