# Generated by Django 2.2.5 on 2021-02-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdb',
            name='status',
            field=models.CharField(choices=[(1, 'on hold'), (2, 'delivered'), (3, 'shipped'), (4, 'ready to ship'), (5, 'cart'), (6, 'paid')], default=1, max_length=10),
        ),
    ]
