# Generated by Django 2.2.5 on 2021-02-06 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0002_auto_20210204_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdb',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='orderdb',
            name='itm_qty',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orderdb',
            name='ord_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderdb',
            name='prod_itm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cat_app.Products'),
        ),
        migrations.AlterField(
            model_name='orderdb',
            name='status',
            field=models.CharField(choices=[(1, 'shipped'), (2, 'delivered'), (3, 'paid'), (5, 'cart')], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='orderdb',
            name='total_amt',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
