# Generated by Django 2.2.5 on 2021-02-12 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0004_auto_20210206_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdb',
            name='ord_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orderuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderdb',
            name='prod_itm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders_for_prod', to='cat_app.Products'),
        ),
    ]
